import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
const headers={"Content-Type":"application/json"};
function key(){const keys=Deno.env.get("SUPABASE_PUBLISHABLE_KEYS");if(keys){const p=JSON.parse(keys);if(p.default)return p.default;}return Deno.env.get("SUPABASE_ANON_KEY")??"";}
const routineTypes=["food","water","activity","sleep"] as const;
Deno.serve(async(req)=>{if(req.method!=="POST")return new Response(JSON.stringify({error:"Method not allowed"}),{status:405,headers});try{const auth=req.headers.get("Authorization")??"";const db=createClient(Deno.env.get("SUPABASE_URL")!,key(),{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const {data:u,error:ue}=await db.auth.getUser();if(ue||!u.user)return new Response(JSON.stringify({error:"Unauthorized"}),{status:401,headers});const owner=u.user.id;const body=await req.json();const petId=String(body?.petId??"");if(!petId)return new Response(JSON.stringify({error:"petId required"}),{status:400,headers});const [{data:pet},{data:vaccines},{data:weights},{data:life}]=await Promise.all([db.from("pets").select("id,name").eq("id",petId).eq("owner_id",owner).maybeSingle(),db.from("vaccines").select("id,vaccine_name,next_due_date").eq("pet_id",petId).eq("owner_id",owner).not("next_due_date","is",null),db.from("weight_entries").select("weight,measured_at").eq("pet_id",petId).eq("owner_id",owner).order("measured_at",{ascending:false}).limit(2),db.from("pet_life_entries").select("id,entry_type,occurred_at").eq("pet_id",petId).eq("owner_id",owner).in("entry_type",routineTypes as unknown as string[]).order("occurred_at",{ascending:false}).limit(100)]);if(!pet)return new Response(JSON.stringify({error:"Pet not found"}),{status:404,headers});const alerts:any[]=[];const now=new Date();for(const v of vaccines??[]){if(!v.next_due_date)continue;const due=new Date(`${v.next_due_date}T12:00:00Z`);const days=Math.ceil((due.getTime()-now.getTime())/86400000);if(days<0)alerts.push({owner_id:owner,pet_id:petId,alert_type:"vaccine_overdue",severity:"high",title:`${v.vaccine_name} gecikmiş görünüyor`,message:`Planlanan tarih ${v.next_due_date}. Veterinerinizle yeni uygulama tarihini doğrulayın.`,source_key:`vaccine_overdue:${v.id}:${v.next_due_date}`});else if(days<=7)alerts.push({owner_id:owner,pet_id:petId,alert_type:"vaccine_due",severity:"medium",title:`${v.vaccine_name} yaklaşıyor`,message:`Planlanan tarih ${v.next_due_date}.`,source_key:`vaccine_due:${v.id}:${v.next_due_date}`});}
if((weights??[]).length>=2){const latest=Number(weights![0].weight),previous=Number(weights![1].weight);if(previous>0){const pct=((latest-previous)/previous)*100;if(Math.abs(pct)>=10)alerts.push({owner_id:owner,pet_id:petId,alert_type:"weight_change",severity:Math.abs(pct)>=20?"high":"medium",title:"Belirgin kilo değişimi kaydedildi",message:`Son iki kayıtta kilo yaklaşık %${Math.abs(pct).toFixed(0)} ${pct>0?"arttı":"azaldı"}. Ölçümü doğrulayın ve beklenmedikse veterinerinizle görüşün.`,source_key:`weight_change:${weights![0].measured_at}:${weights![1].measured_at}`});}}
for(const type of routineTypes){const entries=(life??[]).filter((x:any)=>x.entry_type===type);if(entries.length<2)continue;const latest=new Date(entries[0].occurred_at);const hours=(now.getTime()-latest.getTime())/3600000;const threshold=type==="sleep"?48:72;await db.from("smart_health_alerts").update({status:"resolved",resolved_at:now.toISOString()}).eq("owner_id",owner).eq("pet_id",petId).eq("alert_type",`routine_gap_${type}`).eq("status","active");if(hours>threshold){const labels:any={food:"mama",water:"su",activity:"aktivite",sleep:"uyku"};alerts.push({owner_id:owner,pet_id:petId,alert_type:`routine_gap_${type}`,severity:"low",title:`${labels[type]} kaydında boşluk var`,message:`Son ${labels[type]} kaydının üzerinden ${Math.floor(hours/24)} gün geçti. Bu, ${pet.name}’in rutini aksadı anlamına gelmez; yalnızca Pawly’ta yeni kayıt görünmüyor.`,source_key:`routine_gap:${type}:${entries[0].occurred_at}`});}}
for(const a of alerts){await db.from("smart_health_alerts").upsert(a,{onConflict:"owner_id,source_key",ignoreDuplicates:true});}const {data:active}=await db.from("smart_health_alerts").select("id,alert_type,severity,title,message,status,detected_at").eq("owner_id",owner).eq("pet_id",petId).eq("status","active").order("detected_at",{ascending:false});return new Response(JSON.stringify({alerts:active??[]}),{headers});}catch(e){console.error(e);return new Response(JSON.stringify({error:"Unexpected error"}),{status:500,headers});}});
