import type { SupportedLocale } from './globalization';

const en = {
  title: 'NFC / QR collar', chip: 'Microchip number',
  chipHelp: 'Enter the number from your pet passport or ask your vet to scan the chip. Phones cannot read implanted pet microchips. Saving it here does not register it with an official registry.',
  chipError: 'Check the chip number: 15 or 9 digits, or a 10-character code using 0–9 and A–F.',
  intro: 'A collar tag opens your pet’s contact page without an account. It does not track location.',
  how: 'How to use it',
  steps: [
    'Save a contact number with its country code, then create a collar link.',
    'Save the QR image and print it on a collar tag. For NFC, copy the same link and write it as a URL using an NFC writing app and a writable NDEF tag. Safari cannot write NFC tags.',
    'Hold a compatible phone near the NFC tag and tap the notification, or scan the QR with the camera. An internet connection is needed.',
    'Test it on another phone before attaching it. Turn on Lost mode if needed. Pausing the tag closes the contact page; resuming keeps the same QR and NFC link.',
  ],
  phone: 'Contact phone (with country code)', contactName: 'Contact name (optional)', note: 'Message for the finder (optional)',
  consent: 'I agree to share the pet’s name, species, breed and these contact details with anyone who has the tag link. The chip number, health records and home address stay private.',
  phoneError: 'Enter a valid phone number including + and the country code.', consentError: 'Please confirm the details you want to share.',
  create: 'Create collar link', save: 'Save changes', saved: 'Collar details saved.', error: 'Could not save the tag. Check your connection and try again.',
  loading: 'Loading collar details…', loadError: 'Could not load this tag. Please try again.', retry: 'Try again',
  active: 'Tag active', paused: 'Tag paused', pause: 'Pause tag', resume: 'Resume tag', lost: 'Lost mode',
  lostHelp: 'Shows a clear lost-pet message on the finder page.',
  copy: 'Copy NFC link', copied: 'Link copied.', copyHelp: 'Select and copy the link below.',
  qr: 'Save QR image', qrHelp: 'Keep the white border around the QR when printing. Test the finished tag with a phone.',
  preview: 'Preview finder page', close: 'Close preview',
  demo: 'Demo: you can try the settings here. Nothing is published and no real collar link is created. Use your own account to activate a real tag.',
  demoPreview: 'Demo preview · not a live tag', missing: 'This tag is unavailable or paused. If you found a pet, a veterinary clinic can check its microchip.',
  found: 'Have you found this pet?', lostBanner: 'This pet is missing', call: 'Call the contact', message: 'Send SMS',
  finderHelp: 'Please contact the person below to help this pet get home.',
  privacy: 'Only the details selected by the owner appear here.',
  network: 'The contact page could not be loaded. Check your internet connection and try again.',
  noContact: 'Contact actions are disabled in the demo.', back: 'Open PetCookieGo',
  saving: 'Saving…', newLink: 'Your QR and NFC use the same permanent link.',
};

type TagCopy = { [K in keyof typeof en]: (typeof en)[K] };
export const tagCopy: Record<SupportedLocale, TagCopy> = {
  en,
  tr: {
    title: 'NFC / QR tasma', chip: 'Mikroçip numarası',
    chipHelp: 'Numarayı hayvan pasaportundan girin veya veterinerinizden çipi okutmasını isteyin. Telefonlar deri altındaki hayvan mikroçipini okuyamaz. Buraya kaydetmek resmî sicil kaydı oluşturmaz.',
    chipError: 'Çip numarasını kontrol edin: 15 veya 9 rakam ya da 0–9 ve A–F içeren 10 karakter.',
    intro: 'Tasma etiketi, üyelik gerekmeden dostunuzun iletişim sayfasını açar. Konum takibi yapmaz.',
    how: 'Nasıl kullanılır?',
    steps: [
      'Ülke koduyla bir iletişim numarası girin ve tasma bağlantısını oluşturun.',
      'QR görselini kaydedip tasma etiketine bastırın. NFC için aynı bağlantıyı kopyalayın; bir NFC yazma uygulamasıyla yazılabilir NDEF etikete URL olarak yazın. Safari NFC etikete yazamaz.',
      'Uyumlu telefonu NFC etikete yaklaştırıp bildirime dokunun veya kamerayla QR kodunu okutun. İnternet bağlantısı gerekir.',
      'Tasmaya takmadan önce başka bir telefonla deneyin. Gerekirse Kayıp modunu açın. Etiketi duraklatmak iletişim sayfasını kapatır; yeniden açınca aynı QR ve NFC bağlantısı çalışır.',
    ],
    phone: 'İletişim telefonu (ülke koduyla)', contactName: 'İletişim kurulacak kişi (isteğe bağlı)', note: 'Bulan kişiye mesaj (isteğe bağlı)',
    consent: 'Dostumun adını, türünü, ırkını ve bu iletişim bilgilerini tasma bağlantısına sahip kişilerle paylaşmayı kabul ediyorum. Çip numarası, sağlık kayıtları ve ev adresi gizli kalır.',
    phoneError: 'Başında + ve ülke kodu bulunan geçerli bir telefon numarası girin.', consentError: 'Paylaşılacak bilgileri onaylayın.',
    create: 'Tasma bağlantısı oluştur', save: 'Değişiklikleri kaydet', saved: 'Tasma bilgileri kaydedildi.', error: 'Etiket kaydedilemedi. Bağlantınızı kontrol edip tekrar deneyin.',
    loading: 'Tasma bilgileri yükleniyor…', loadError: 'Etiket yüklenemedi. Tekrar deneyin.', retry: 'Tekrar dene',
    active: 'Etiket aktif', paused: 'Etiket duraklatıldı', pause: 'Etiketi duraklat', resume: 'Etiketi yeniden aç', lost: 'Kayıp modu',
    lostHelp: 'Bulan kişinin ekranında belirgin bir kayıp uyarısı gösterir.',
    copy: 'NFC bağlantısını kopyala', copied: 'Bağlantı kopyalandı.', copyHelp: 'Aşağıdaki bağlantıyı seçip kopyalayın.',
    qr: 'QR görselini kaydet', qrHelp: 'Bastırırken QR etrafındaki beyaz boşluğu koruyun. Hazır etiketi telefonla test edin.',
    preview: 'Bulan kişinin ekranını gör', close: 'Önizlemeyi kapat',
    demo: 'Demo: ayarları burada deneyebilirsiniz. Bilgiler yayımlanmaz ve gerçek tasma bağlantısı oluşturulmaz. Gerçek etiketi kendi hesabınızda etkinleştirin.',
    demoPreview: 'Demo önizlemesi · gerçek etiket değildir', missing: 'Bu etiket kullanılamıyor veya duraklatılmış. Bir hayvan bulduysanız veteriner kliniği mikroçipini kontrol edebilir.',
    found: 'Bu dostumuzu mu buldunuz?', lostBanner: 'Bu dostumuz kayıp', call: 'İletişim kişisini ara', message: 'SMS gönder',
    finderHelp: 'Dostumuzun evine dönmesine yardımcı olmak için aşağıdaki kişiyle iletişime geçin.',
    privacy: 'Burada yalnızca sahibinin paylaşmayı seçtiği bilgiler görünür.',
    network: 'İletişim sayfası yüklenemedi. İnternet bağlantınızı kontrol edip tekrar deneyin.',
    noContact: 'Demoda arama ve SMS kapalıdır.', back: 'PetCookieGo’yu aç', saving: 'Kaydediliyor…', newLink: 'QR ve NFC aynı kalıcı bağlantıyı kullanır.',
  },
  de: {
    title: 'NFC- / QR-Halsband', chip: 'Mikrochipnummer',
    chipHelp: 'Trage die Nummer aus dem Tierpass ein oder lasse den Chip beim Tierarzt auslesen. Handys können implantierte Tierchips nicht lesen. Das Speichern hier ersetzt keine offizielle Registrierung.',
    chipError: 'Prüfe die Chipnummer: 15 oder 9 Ziffern oder 10 Zeichen aus 0–9 und A–F.',
    intro: 'Die Halsbandmarke öffnet die Kontaktseite deines Tieres ohne Anmeldung. Sie bietet keine Ortung.',
    how: 'So funktioniert es',
    steps: [
      'Speichere eine Telefonnummer mit Ländervorwahl und erstelle den Halsbandlink.',
      'Speichere das QR-Bild und drucke es auf eine Halsbandmarke. Für NFC kopierst du denselben Link und schreibst ihn mit einer NFC-Schreib-App als URL auf einen beschreibbaren NDEF-Tag. Safari kann keine NFC-Tags beschreiben.',
      'Halte ein kompatibles Handy an den NFC-Tag und tippe auf die Meldung oder scanne den QR-Code mit der Kamera. Eine Internetverbindung ist nötig.',
      'Teste die Marke vor dem Anbringen mit einem anderen Handy. Aktiviere bei Bedarf den Vermisst-Modus. Pausieren schließt die Kontaktseite; nach dem Fortsetzen gilt derselbe QR- und NFC-Link.',
    ],
    phone: 'Kontakttelefon (mit Ländervorwahl)', contactName: 'Kontaktname (optional)', note: 'Nachricht für den Finder (optional)',
    consent: 'Ich stimme zu, Name, Tierart, Rasse und diese Kontaktdaten mit allen zu teilen, die den Markenlink haben. Chipnummer, Gesundheitsdaten und Wohnadresse bleiben privat.',
    phoneError: 'Gib eine gültige Telefonnummer mit + und Ländervorwahl ein.', consentError: 'Bitte bestätige die freizugebenden Angaben.',
    create: 'Halsbandlink erstellen', save: 'Änderungen speichern', saved: 'Halsbanddaten gespeichert.', error: 'Die Marke konnte nicht gespeichert werden. Prüfe deine Verbindung und versuche es erneut.',
    loading: 'Halsbanddaten werden geladen…', loadError: 'Die Marke konnte nicht geladen werden. Versuche es erneut.', retry: 'Erneut versuchen',
    active: 'Marke aktiv', paused: 'Marke pausiert', pause: 'Marke pausieren', resume: 'Marke fortsetzen', lost: 'Vermisst-Modus',
    lostHelp: 'Zeigt auf der Finderseite einen deutlichen Vermisst-Hinweis.',
    copy: 'NFC-Link kopieren', copied: 'Link kopiert.', copyHelp: 'Wähle den Link unten aus und kopiere ihn.',
    qr: 'QR-Bild speichern', qrHelp: 'Lasse beim Drucken den weißen Rand um den QR-Code frei. Teste die fertige Marke mit einem Handy.',
    preview: 'Finderseite ansehen', close: 'Vorschau schließen',
    demo: 'Demo: Hier kannst du die Einstellungen ausprobieren. Es wird nichts veröffentlicht und kein echter Halsbandlink erstellt. Aktiviere eine echte Marke in deinem eigenen Konto.',
    demoPreview: 'Demo-Vorschau · keine aktive Marke', missing: 'Diese Marke ist nicht verfügbar oder pausiert. Wenn du ein Tier gefunden hast, kann eine Tierarztpraxis seinen Mikrochip prüfen.',
    found: 'Hast du dieses Tier gefunden?', lostBanner: 'Dieses Tier wird vermisst', call: 'Kontaktperson anrufen', message: 'SMS senden',
    finderHelp: 'Bitte kontaktiere die Person unten, damit dieses Tier nach Hause findet.',
    privacy: 'Hier erscheinen nur die vom Halter freigegebenen Angaben.',
    network: 'Die Kontaktseite konnte nicht geladen werden. Prüfe deine Internetverbindung und versuche es erneut.',
    noContact: 'Anrufe und SMS sind in der Demo deaktiviert.', back: 'PetCookieGo öffnen', saving: 'Wird gespeichert…', newLink: 'QR und NFC verwenden denselben dauerhaften Link.',
  },
  es: {
    title: 'Collar NFC / QR', chip: 'Número de microchip',
    chipHelp: 'Introduce el número del pasaporte de tu mascota o pide al veterinario que lea el chip. Los teléfonos no pueden leer microchips implantados. Guardarlo aquí no lo inscribe en un registro oficial.',
    chipError: 'Comprueba el chip: 15 o 9 dígitos, o un código de 10 caracteres con 0–9 y A–F.',
    intro: 'La placa abre la página de contacto de tu mascota sin iniciar sesión. No rastrea su ubicación.',
    how: 'Cómo usarlo',
    steps: [
      'Guarda un teléfono con su prefijo internacional y crea un enlace para el collar.',
      'Guarda la imagen QR e imprímela en una placa. Para NFC, copia el mismo enlace y grábalo como URL en una etiqueta NDEF regrabable con una app de escritura NFC. Safari no puede escribir etiquetas NFC.',
      'Acerca un teléfono compatible a la etiqueta NFC y toca la notificación, o escanea el QR con la cámara. Se necesita conexión a internet.',
      'Pruébala con otro teléfono antes de ponerla en el collar. Activa el modo perdido si hace falta. Pausar la placa cierra la página; al reactivarla, funciona el mismo enlace QR y NFC.',
    ],
    phone: 'Teléfono de contacto (con prefijo internacional)', contactName: 'Persona de contacto (opcional)', note: 'Mensaje para quien la encuentre (opcional)',
    consent: 'Acepto compartir el nombre, especie, raza y estos datos de contacto con quien tenga el enlace. El número de chip, historial médico y domicilio se mantienen privados.',
    phoneError: 'Introduce un teléfono válido con + y el prefijo internacional.', consentError: 'Confirma los datos que quieres compartir.',
    create: 'Crear enlace del collar', save: 'Guardar cambios', saved: 'Datos del collar guardados.', error: 'No se pudo guardar la placa. Revisa tu conexión e inténtalo de nuevo.',
    loading: 'Cargando datos del collar…', loadError: 'No se pudo cargar la placa. Inténtalo de nuevo.', retry: 'Reintentar',
    active: 'Placa activa', paused: 'Placa en pausa', pause: 'Pausar placa', resume: 'Reactivar placa', lost: 'Modo perdido',
    lostHelp: 'Muestra un aviso claro de mascota perdida en la página de contacto.',
    copy: 'Copiar enlace NFC', copied: 'Enlace copiado.', copyHelp: 'Selecciona y copia el enlace de abajo.',
    qr: 'Guardar imagen QR', qrHelp: 'Conserva el margen blanco del QR al imprimir. Prueba la placa terminada con un teléfono.',
    preview: 'Ver página de contacto', close: 'Cerrar vista previa',
    demo: 'Demo: puedes probar los ajustes aquí. No se publica nada ni se crea un enlace real. Usa tu cuenta para activar una placa real.',
    demoPreview: 'Vista previa demo · no es una placa activa', missing: 'Esta placa no está disponible o está en pausa. Si encontraste una mascota, una clínica veterinaria puede comprobar su microchip.',
    found: '¿Encontraste esta mascota?', lostBanner: 'Esta mascota está perdida', call: 'Llamar al contacto', message: 'Enviar SMS',
    finderHelp: 'Contacta con la persona indicada para ayudar a esta mascota a volver a casa.',
    privacy: 'Solo se muestran los datos que el responsable decidió compartir.',
    network: 'No se pudo cargar la página. Revisa tu conexión a internet e inténtalo de nuevo.',
    noContact: 'Las llamadas y los SMS están desactivados en la demo.', back: 'Abrir PetCookieGo', saving: 'Guardando…', newLink: 'QR y NFC usan el mismo enlace permanente.',
  },
  ja: {
    title: 'NFC / QR 首輪タグ', chip: 'マイクロチップ番号',
    chipHelp: 'ペットの証明書に記載された番号を入力するか、動物病院で読み取ってもらってください。スマートフォンでは埋め込み型のペット用チップを読み取れません。ここへの保存は公的登録の代わりにはなりません。',
    chipError: '番号を確認してください。15桁または9桁の数字、もしくは0〜9とA〜Fの10文字に対応しています。',
    intro: '首輪タグから、ログインせずにペットの連絡先ページを開けます。位置の追跡機能はありません。',
    how: '使い方',
    steps: [
      '国番号付きの連絡先電話番号を保存し、首輪用リンクを作成します。',
      'QR画像を保存して首輪のタグに印刷します。NFCの場合は同じリンクをコピーし、NFC書き込みアプリで書き込み可能なNDEFタグにURLとして保存します。SafariではNFCタグに書き込めません。',
      '対応するスマートフォンをNFCタグに近づけて通知をタップするか、カメラでQRを読み取ります。インターネット接続が必要です。',
      '首輪に付ける前に別のスマートフォンで確認してください。必要に応じて迷子モードを有効にします。タグを停止すると連絡先ページが閉じ、再開すると同じQRとNFCリンクが使えます。',
    ],
    phone: '連絡先電話番号（国番号付き）', contactName: '連絡先の名前（任意）', note: '発見者へのメッセージ（任意）',
    consent: 'タグのリンクを知っている人に、ペットの名前、種類、品種とこの連絡先を公開することに同意します。チップ番号、健康記録、自宅住所は公開されません。',
    phoneError: '+と国番号を含む有効な電話番号を入力してください。', consentError: '公開する情報に同意してください。',
    create: '首輪用リンクを作成', save: '変更を保存', saved: '首輪タグの情報を保存しました。', error: 'タグを保存できませんでした。接続を確認してもう一度お試しください。',
    loading: 'タグ情報を読み込み中…', loadError: 'タグを読み込めませんでした。もう一度お試しください。', retry: '再試行',
    active: 'タグ有効', paused: 'タグ停止中', pause: 'タグを停止', resume: 'タグを再開', lost: '迷子モード',
    lostHelp: '発見者のページに迷子であることをわかりやすく表示します。',
    copy: 'NFCリンクをコピー', copied: 'リンクをコピーしました。', copyHelp: '下のリンクを選択してコピーしてください。',
    qr: 'QR画像を保存', qrHelp: '印刷時はQRの周囲に白い余白を残してください。完成したタグをスマートフォンで確認してください。',
    preview: '発見者のページを確認', close: 'プレビューを閉じる',
    demo: 'デモでは設定を試せます。情報は公開されず、実際の首輪用リンクも作成されません。本物のタグはご自身のアカウントで有効にしてください。',
    demoPreview: 'デモプレビュー · 実際のタグではありません', missing: 'このタグは利用できないか停止中です。ペットを見つけた場合は、動物病院でマイクロチップを確認できます。',
    found: 'このペットを見つけましたか？', lostBanner: 'このペットは迷子です', call: '連絡先に電話', message: 'SMSを送信',
    finderHelp: 'ペットが家に帰れるよう、以下の連絡先へご連絡ください。',
    privacy: '飼い主が公開を選んだ情報だけが表示されます。',
    network: 'ページを読み込めませんでした。インターネット接続を確認してもう一度お試しください。',
    noContact: 'デモでは電話とSMSは使えません。', back: 'PetCookieGoを開く', saving: '保存中…', newLink: 'QRとNFCには同じ固定リンクを使います。',
  },
};
