import React,{useEffect,useMemo,useState}from'react';
import{ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View}from'react-native';
import{evaluateSmartHealthAlerts,type SmartHealthAlert}from'../lib/healthBrain';
import{detectLocalHealthTrends,type HealthTrend}from'../lib/healthTrends';
import{buildTodayLifeMetrics}from'../lib/lifeDashboard';
import{addLifeEntry,loadPlatformSnapshot,type PetLifeEntryType,type PlatformSnapshot}from'../lib/platformData';
import type{Pet}from'../types';
import{colors,shadow}from'../theme';
import{usePreferences}from'../context/PreferencesContext';

const emptySnapshot:PlatformSnapshot={weights:[],lifeEntries:[],memberCount:0,activePassportCount:0,passports:[],pro:{plan:'free'}};
const copy={
tr:{title:'Bugün nasıl gidiyor?',sub:'Beslenme, su, aktivite, uyku ve bakım rutinlerini tek yerde takip edin.',summary:'Bugünün özeti',quick:'Hızlı kayıt',oneTap:'Tek dokunuş sağlık kaydı',oneTapHint:'Sık kullanılan olayları form doldurmadan kaydedin.',medication:'İlaç verildi',parasite:'Parazit uygulandı',symptom:'Belirti fark ettim',vetVisit:'Veterinere gittik',saved:'Kaydedildi',savedText:'Sağlık kaydı eklendi.',unit:'Birim',note:'Not (opsiyonel)',save:'Bugüne ekle',saving:'Kaydediliyor…',alerts:'Akıllı sağlık uyarıları',trends:'Sağlık trendleri',ok:'✓ Aktif uyarı yok',okText:'PetVitals kayıtları açılışta ve yeni Life kaydı sonrasında otomatik kontrol eder.',trendOk:'✓ Dikkat çeken tekrar eden bir trend yok',trendDisc:'Trendler kayıtlarınızdaki tekrarları ve değişimleri gösterir; tanı değildir.',symptomTrend:(n:number)=>`Son 90 günde ${n} kez belirti kaydı girdiniz. Tekrarlayan bir durum olabilir; devam ederse veterinerinizle paylaşın.`,vetTrend:(n:number)=>`Son 90 günde ${n} veteriner ziyareti kaydı var. Ziyaret sıklığı arttıysa geçmiş kayıtlarla birlikte değerlendirin.`,weightUp:(p:number)=>`Son 6 ay içindeki kayıtlı ağırlık yaklaşık %${p} arttı.`,weightDown:(p:number)=>`Son 6 ay içindeki kayıtlı ağırlık yaklaşık %${p} azaldı.`,none:'Henüz kayıt yok',record:'kayıt',real:'Gerçek hesap gerekli',realText:'Life kayıtları gerçek hesabınızda saklanır.',fail:'Kaydedilemedi',failText:'Life kaydı eklenemedi.',disc:'Smart Alerts kayıtlarınızdaki değişimleri ve kayıt boşluklarını görünür hale getirir; veteriner tanısı değildir.',types:['Mama','Su','Aktivite','Uyku','Bakım','Parazit','Ruh hali'],units:['g','ml','dk','saat','','',''],ph:['Örn. 120','Örn. 250','Örn. 45','Örn. 8','Not','Uygulama adı/not','Mutlu, sakin...']},
en:{title:'How is today going?',sub:'Track food, water, activity, sleep and care routines in one place.',summary:"Today's summary",quick:'Quick log',oneTap:'One-tap health log',oneTapHint:'Save common health events without filling out a form.',medication:'Medication given',parasite:'Parasite treatment',symptom:'Symptom noticed',vetVisit:'Vet visit',saved:'Saved',savedText:'Health event added.',unit:'Unit',note:'Note (optional)',save:'Add to today',saving:'Saving…',alerts:'Smart health alerts',trends:'Health trends',ok:'✓ No active alerts',okText:'PetVitals checks your records at launch and after each new Life entry.',trendOk:'✓ No notable recurring trend detected',trendDisc:'Trends highlight repeated events and changes in your records; they are not a diagnosis.',symptomTrend:(n:number)=>`You logged symptoms ${n} times in the last 90 days. If this continues, consider sharing the pattern with your veterinarian.`,vetTrend:(n:number)=>`You logged ${n} vet visits in the last 90 days. If visit frequency is increasing, review the pattern with your records.`,weightUp:(p:number)=>`Recorded weight increased by about ${p}% over the last 6 months.`,weightDown:(p:number)=>`Recorded weight decreased by about ${p}% over the last 6 months.`,none:'No records yet',record:'records',real:'Account required',realText:'Life entries are stored in your real account.',fail:'Could not save',failText:'Life entry could not be added.',disc:'Smart Alerts highlight changes and gaps in your records; they are not a veterinary diagnosis.',types:['Food','Water','Activity','Sleep','Grooming','Parasite','Mood'],units:['g','ml','min','hours','','',''],ph:['e.g. 120','e.g. 250','e.g. 45','e.g. 8','Note','Treatment/name note','Happy, calm...']},
de:{title:'Wie läuft der Tag?',sub:'Futter, Wasser, Aktivität, Schlaf und Pflege an einem Ort verfolgen.',summary:'Heutige Übersicht',quick:'Schnelleingabe',oneTap:'Gesundheit mit einem Tipp',oneTapHint:'Häufige Gesundheitsereignisse ohne Formular speichern.',medication:'Medikament gegeben',parasite:'Parasitenbehandlung',symptom:'Symptom bemerkt',vetVisit:'Tierarztbesuch',saved:'Gespeichert',savedText:'Gesundheitsereignis wurde hinzugefügt.',unit:'Einheit',note:'Notiz (optional)',save:'Für heute hinzufügen',saving:'Speichern…',alerts:'Intelligente Gesundheitswarnungen',trends:'Gesundheitstrends',ok:'✓ Keine aktiven Warnungen',okText:'PetVitals prüft Ihre Daten beim Start und nach neuen Life-Einträgen.',trendOk:'✓ Kein auffälliger wiederkehrender Trend erkannt',trendDisc:'Trends zeigen wiederholte Ereignisse und Veränderungen in Ihren Daten; sie sind keine Diagnose.',symptomTrend:(n:number)=>`In den letzten 90 Tagen wurden ${n} Symptome protokolliert. Wenn das anhält, teilen Sie das Muster mit Ihrem Tierarzt.`,vetTrend:(n:number)=>`In den letzten 90 Tagen wurden ${n} Tierarztbesuche protokolliert. Prüfen Sie eine steigende Häufigkeit zusammen mit dem Verlauf.`,weightUp:(p:number)=>`Das erfasste Gewicht ist in den letzten 6 Monaten um etwa ${p}% gestiegen.`,weightDown:(p:number)=>`Das erfasste Gewicht ist in den letzten 6 Monaten um etwa ${p}% gesunken.`,none:'Noch keine Einträge',record:'Einträge',real:'Konto erforderlich',realText:'Life-Einträge werden in Ihrem echten Konto gespeichert.',fail:'Speichern fehlgeschlagen',failText:'Life-Eintrag konnte nicht hinzugefügt werden.',disc:'Smart Alerts zeigen Änderungen und Lücken in Ihren Daten; sie sind keine tierärztliche Diagnose.',types:['Futter','Wasser','Aktivität','Schlaf','Pflege','Parasit','Stimmung'],units:['g','ml','Min','Stunden','','',''],ph:['z. B. 120','z. B. 250','z. B. 45','z. B. 8','Notiz','Anwendung/Notiz','Glücklich, ruhig...']},
es:{title:'¿Cómo va el día?',sub:'Controla comida, agua, actividad, sueño y cuidados en un solo lugar.',summary:'Resumen de hoy',quick:'Registro rápido',oneTap:'Registro de salud con un toque',oneTapHint:'Guarda eventos frecuentes sin rellenar un formulario.',medication:'Medicación administrada',parasite:'Tratamiento antiparasitario',symptom:'Noté un síntoma',vetVisit:'Visita al veterinario',saved:'Guardado',savedText:'Evento de salud añadido.',unit:'Unidad',note:'Nota (opcional)',save:'Añadir a hoy',saving:'Guardando…',alerts:'Alertas inteligentes de salud',trends:'Tendencias de salud',ok:'✓ No hay alertas activas',okText:'PetVitals revisa tus registros al abrir y tras cada nueva entrada de Life.',trendOk:'✓ No se detectan tendencias repetidas destacables',trendDisc:'Las tendencias muestran repeticiones y cambios en tus registros; no son un diagnóstico.',symptomTrend:(n:number)=>`Registraste síntomas ${n} veces en los últimos 90 días. Si continúa, comparte el patrón con tu veterinario.`,vetTrend:(n:number)=>`Registraste ${n} visitas al veterinario en los últimos 90 días. Si aumenta la frecuencia, revisa el patrón junto con el historial.`,weightUp:(p:number)=>`El peso registrado aumentó aproximadamente un ${p}% en los últimos 6 meses.`,weightDown:(p:number)=>`El peso registrado disminuyó aproximadamente un ${p}% en los últimos 6 meses.`,none:'Aún no hay registros',record:'registros',real:'Se requiere una cuenta',realText:'Los registros de Life se guardan en tu cuenta real.',fail:'No se pudo guardar',failText:'No se pudo añadir el registro de Life.',disc:'Smart Alerts muestra cambios y huecos en tus registros; no es un diagnóstico veterinario.',types:['Comida','Agua','Actividad','Sueño','Cuidado','Parásito','Ánimo'],units:['g','ml','min','horas','','',''],ph:['ej. 120','ej. 250','ej. 45','ej. 8','Nota','Aplicación/nota','Feliz, tranquilo...']}};
const keys:PetLifeEntryType[]=['food','water','activity','sleep','grooming','parasite','mood'];
type QuickAction='medication'|'parasite'|'symptom'|'vet_visit';

export function LifeScreen({pets,userId,demoMode}:{pets:Pet[];userId?:string;demoMode:boolean}){
 const{language}=usePreferences();const c=copy[language];
 const quickTypes=keys.map((key,i)=>({key,label:c.types[i],placeholder:c.ph[i],unit:c.units[i]}));
 const[selectedPetId,setSelectedPetId]=useState(pets[0]?.id??'');
 const[snapshot,setSnapshot]=useState<PlatformSnapshot>(emptySnapshot);const[alerts,setAlerts]=useState<SmartHealthAlert[]>([]);
 const[selectedType,setSelectedType]=useState<PetLifeEntryType>('activity');const[value,setValue]=useState('');const[unit,setUnit]=useState<string>(c.units[2]);const[note,setNote]=useState('');const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[quickSaving,setQuickSaving]=useState<QuickAction|null>(null);
 const selectedPet=pets.find(p=>p.id===selectedPetId)??pets[0];
 const metrics=useMemo(()=>buildTodayLifeMetrics(snapshot.lifeEntries),[snapshot.lifeEntries]);
 const trends=useMemo(()=>detectLocalHealthTrends(snapshot.lifeEntries,snapshot.weights),[snapshot.lifeEntries,snapshot.weights]);
 useEffect(()=>{if(!pets.some(p=>p.id===selectedPetId))setSelectedPetId(pets[0]?.id??'');},[pets,selectedPetId]);
 async function refresh(){if(!selectedPet||!userId||demoMode){setSnapshot(emptySnapshot);setAlerts([]);return;}setLoading(true);try{const[s,a]=await Promise.all([loadPlatformSnapshot(userId,selectedPet.id),evaluateSmartHealthAlerts(selectedPet.id)]);setSnapshot(s);setAlerts(a);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[selectedPet?.id,userId,demoMode]);
 function chooseType(type:PetLifeEntryType){setSelectedType(type);const p=quickTypes.find(x=>x.key===type);setUnit(p?.unit??'');setValue('');setNote('');}
 async function save(){if(!selectedPet||!userId||demoMode){Alert.alert(c.real,c.realText);return;}const numeric=value.trim()?Number(value.replace(',','.')):undefined;setSaving(true);try{await addLifeEntry(userId,selectedPet.id,{entryType:selectedType,valueNumeric:Number.isFinite(numeric)?numeric:undefined,valueText:Number.isFinite(numeric)?undefined:value.trim()||undefined,unit,notes:note});setValue('');setNote('');await refresh();}catch(e){Alert.alert(c.fail,e instanceof Error?e.message:c.failText);}finally{setSaving(false);}}
 async function saveQuick(action:QuickAction){if(!selectedPet||!userId||demoMode){Alert.alert(c.real,c.realText);return;}setQuickSaving(action);try{const entryType:PetLifeEntryType=action==='parasite'?'parasite':'custom';await addLifeEntry(userId,selectedPet.id,{entryType,valueText:`quick:${action}`});await refresh();Alert.alert(c.saved,c.savedText);}catch(e){Alert.alert(c.fail,e instanceof Error?e.message:c.failText);}finally{setQuickSaving(null);}}
 function trendText(t:HealthTrend){if(t.kind==='recurring_symptom')return c.symptomTrend(t.count??0);if(t.kind==='frequent_vet_visits')return c.vetTrend(t.count??0);const p=Math.round(t.percent??0);return t.direction==='down'?c.weightDown(p):c.weightUp(p);}
 const quickActions:[QuickAction,string,string][]=[['medication','💊',c.medication],['parasite','🛡️',c.parasite],['symptom','⚠️',c.symptom],['vet_visit','🩺',c.vetVisit]];
 return<View style={s.page}>
  <Text style={s.eyebrow}>PETVITALS LIFE</Text><Text style={s.title}>{c.title}</Text><Text style={s.sub}>{c.sub}</Text>
  {pets.length>1?<View style={s.petPicker}>{pets.map(p=><Pressable key={p.id} onPress={()=>setSelectedPetId(p.id)} style={[s.petChip,selectedPet?.id===p.id&&s.active]}><Text style={[s.petText,selectedPet?.id===p.id&&s.activeText]}>{p.name}</Text></Pressable>)}</View>:null}
  {loading?<ActivityIndicator color={colors.primary} style={{marginTop:18}}/>:null}
  <Text style={s.section}>{c.summary}</Text><View style={s.grid}>{metrics.filter(m=>m.type!=='custom').map((m,i)=><View key={m.type} style={s.metric}><Text style={s.icon}>{m.icon}</Text><Text style={s.mutedBold}>{c.types[i]??m.label}</Text><Text style={s.value}>{m.total!=null?`${Number(m.total.toFixed(1))}${m.unit?` ${m.unit}`:''}`:m.latestText||'—'}</Text><Text style={s.small}>{m.count?`${m.count} ${c.record}`:c.none}</Text></View>)}</View>
  <Text style={s.section}>{c.oneTap}</Text><Text style={s.subtle}>{c.oneTapHint}</Text><View style={s.quickGrid}>{quickActions.map(([key,icon,label])=><Pressable disabled={quickSaving!==null} key={key} onPress={()=>saveQuick(key)} style={s.quickButton}><Text style={s.quickIcon}>{quickSaving===key?'…':icon}</Text><Text style={s.quickLabel}>{label}</Text></Pressable>)}</View>
  <Text style={s.section}>{c.trends}</Text>{trends.length===0?<View style={s.ok}><Text style={s.okTitle}>{c.trendOk}</Text></View>:trends.map(t=><View key={t.id} style={s.trend}><Text style={s.severity}>{t.severity.toUpperCase()}</Text><Text style={s.warnTitle}>{trendText(t)}</Text></View>)}<Text style={s.disc}>{c.trendDisc}</Text>
  <Text style={s.section}>{c.quick}</Text><View style={s.chips}>{quickTypes.map(x=><Pressable key={x.key} onPress={()=>chooseType(x.key)} style={[s.chip,selectedType===x.key&&s.active]}><Text style={[s.chipText,selectedType===x.key&&s.activeText]}>{x.label}</Text></Pressable>)}</View><View style={s.form}><TextInput keyboardType={['food','water','activity','sleep'].includes(selectedType)?'decimal-pad':'default'} placeholder={quickTypes.find(x=>x.key===selectedType)?.placeholder} placeholderTextColor={colors.muted} value={value} onChangeText={setValue} style={s.input}/><TextInput placeholder={c.unit} placeholderTextColor={colors.muted} value={unit} onChangeText={setUnit} style={s.input}/><TextInput multiline placeholder={c.note} placeholderTextColor={colors.muted} value={note} onChangeText={setNote} style={[s.input,s.multi]}/><Pressable disabled={saving} onPress={save} style={s.button}><Text style={s.buttonText}>{saving?c.saving:c.save}</Text></Pressable></View>
  <Text style={s.section}>{c.alerts}</Text>{alerts.length===0?<View style={s.ok}><Text style={s.okTitle}>{c.ok}</Text><Text style={s.okText}>{c.okText}</Text></View>:alerts.map(a=><View key={a.id} style={s.warn}><Text style={s.severity}>{a.severity.toUpperCase()}</Text><Text style={s.warnTitle}>{a.title}</Text><Text style={s.okText}>{a.message}</Text></View>)}<Text style={s.disc}>{c.disc}</Text>
 </View>;
}
const s=StyleSheet.create({page:{padding:22},eyebrow:{color:colors.primary,fontSize:11,fontWeight:'900',letterSpacing:1.2},title:{color:colors.text,fontSize:30,fontWeight:'900',marginTop:6},sub:{color:colors.muted,lineHeight:20,marginTop:7},subtle:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:-5},petPicker:{flexDirection:'row',gap:8,marginTop:16},petChip:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:999,borderWidth:1,paddingHorizontal:12,paddingVertical:8},petText:{color:colors.text,fontWeight:'700'},active:{backgroundColor:colors.primary,borderColor:colors.primary},activeText:{color:colors.white},section:{color:colors.text,fontSize:19,fontWeight:'900',marginBottom:11,marginTop:24},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{...shadow,backgroundColor:colors.surface,borderColor:colors.border,borderRadius:17,borderWidth:1,padding:14,width:'48%'},icon:{fontSize:20},mutedBold:{color:colors.muted,fontSize:11,fontWeight:'800',marginTop:7},value:{color:colors.text,fontSize:19,fontWeight:'900',marginTop:4},small:{color:colors.muted,fontSize:10,marginTop:3},quickGrid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:12},quickButton:{...shadow,alignItems:'center',backgroundColor:colors.surface,borderColor:colors.border,borderRadius:17,borderWidth:1,minHeight:92,padding:13,width:'48%'},quickIcon:{fontSize:23},quickLabel:{color:colors.text,fontSize:12,fontWeight:'900',marginTop:8,textAlign:'center'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:999,borderWidth:1,paddingHorizontal:11,paddingVertical:8},chipText:{color:colors.muted,fontSize:11,fontWeight:'800'},form:{backgroundColor:colors.surface,borderColor:colors.border,borderRadius:18,borderWidth:1,marginTop:12,padding:14},input:{backgroundColor:colors.background,borderColor:colors.border,borderRadius:12,borderWidth:1,color:colors.text,marginBottom:9,paddingHorizontal:12,paddingVertical:11},multi:{minHeight:72,textAlignVertical:'top'},button:{alignItems:'center',backgroundColor:colors.primary,borderRadius:13,paddingVertical:12},buttonText:{color:colors.white,fontWeight:'900'},ok:{backgroundColor:'#EEF7F4',borderRadius:16,padding:15},okTitle:{color:colors.primaryDark,fontWeight:'900'},okText:{color:colors.muted,lineHeight:18,marginTop:5},warn:{backgroundColor:'#FFF7ED',borderRadius:16,marginBottom:9,padding:15},trend:{backgroundColor:'#F3F6FF',borderRadius:16,marginBottom:9,padding:15},severity:{color:colors.accent,fontSize:10,fontWeight:'900'},warnTitle:{color:colors.text,fontSize:14,fontWeight:'900',lineHeight:20,marginTop:3},disc:{color:colors.muted,fontSize:10,lineHeight:15,marginTop:12}});
